[phases.setup]
nixPkgs = ["nodejs_20", "python311"]
aptPkgs = []

[phases.install]
dependsOn = ["setup"]
cmds = [
    "npm install --prefix frontend",
    "pip install ."
]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build --prefix frontend"]
